# Generated by Django 4.1.5 on 2023-01-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='категория курсов')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='категория')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='категория')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.servicecategory', verbose_name='категория')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24, verbose_name='имя')),
                ('last_name', models.CharField(max_length=24, verbose_name='фамилия')),
                ('image_url', models.ImageField(max_length=64, upload_to='service_images', verbose_name='изображение')),
                ('description', models.TextField(verbose_name='описание')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email')),
                ('tg', models.CharField(blank=True, max_length=24, unique=True, verbose_name='телеграм')),
                ('is_top', models.BooleanField(default=False, verbose_name='топ')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('sub_category', models.ManyToManyField(to='admin_app.servicesubcategory', verbose_name='категории')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='курс')),
                ('description', models.TextField(verbose_name='описание')),
                ('url', models.URLField(verbose_name='ссылка')),
                ('image_url', models.ImageField(max_length=64, upload_to='service_images', verbose_name='изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.coursecategory', verbose_name='категория')),
            ],
        ),
    ]
