# Generated by Django 4.1.5 on 2023-01-13 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['-is_active', 'title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='servicesubcategory',
            options={'ordering': ['-is_active', 'title'], 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='serviceuser',
            options={'ordering': ['-is_active', 'updated_at'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='serviceuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='время добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='последнее обновление'),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='image_url',
            field=models.ImageField(max_length=64, upload_to='service_img', verbose_name='изображение'),
        ),
    ]
