# Generated by Django 4.1.5 on 2023-01-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuser',
            name='image_url',
            field=models.ImageField(blank=True, max_length=64, upload_to='service_img', verbose_name='изображение'),
        ),
    ]
