# Generated by Django 4.1.5 on 2023-01-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_alter_serviceuser_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesubcategory',
            options={'ordering': ['-is_active', 'title', 'category'], 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
    ]
