# Generated by Django 4.1.5 on 2023-01-19 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_alter_servicesubcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service_app.servicecategory', verbose_name='категория'),
        ),
    ]
