# Generated by Django 4.1.5 on 2023-01-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0006_alter_servicesubcategory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesubcategory',
            options={'ordering': ['-is_active', 'category', 'title'], 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='serviceuser',
            options={'ordering': ['is_top', '-is_active', 'updated_at'], 'verbose_name': 'Резидент', 'verbose_name_plural': 'Резиденты'},
        ),
        migrations.AddField(
            model_name='serviceuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='телефон'),
        ),
        migrations.AddField(
            model_name='serviceuser',
            name='web_url',
            field=models.URLField(blank=True, verbose_name='вебсайт'),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='image_url',
            field=models.ImageField(default='service_img/default.jpg', max_length=64, upload_to='service_img', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='tg',
            field=models.CharField(max_length=24, unique=True, verbose_name='телеграм'),
        ),
    ]
