# Generated by Django 4.1.5 on 2023-01-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=24, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='title',
            field=models.CharField(max_length=24, verbose_name='категория'),
        ),
    ]
