# Generated by Django 4.1.5 on 2023-01-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_course_created_at_course_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.ImageField(max_length=64, upload_to='course_images', verbose_name='изображение'),
        ),
    ]
