# Generated by Django 4.1.5 on 2023-01-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_alter_course_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.ImageField(max_length=64, upload_to='course_img', verbose_name='изображение'),
        ),
    ]
