# Generated by Django 4.1.5 on 2023-01-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_alter_course_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-is_active', 'updated_at'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'ordering': ['-is_active', 'title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.ImageField(default='course_img/default.jpg', max_length=64, upload_to='course_img', verbose_name='изображение'),
        ),
    ]
